[tools]
gradle = "8.5"
java = "11"

[tasks.lint]
run = "./gradlew lint"

[tasks.test]
run = "./gradlew test"

[tasks.build]
run = "./gradlew build"

[tasks.all]
depends = ["lint", "test", "build"]
run = "echo \"OK, done!\""
